from dotenv import load_dotenv
import os
load_dotenv()
# AWS_ACCESS_KEY = ""
# AWS_SECRET_KEY = ""

METACULUS_KEY = os.getenv("METACULUS_KEY")
MANIFOLD_KEY = os.getenv("MANIFOLD_KEY")
POLYMARKET_KEY = os.getenv("POLYMARKET_KEY")
CRYPTO_PRIVATE_KEY = os.getenv("CRYPTO_PRIVATE_KEY")
EMAIL = os.getenv("EMAIL")
GJOPEN_CSET_PASSWORD = os.getenv("GJOPEN_CSET_PASSWORD")

# Proxy settings
HTTP_PROXY = os.getenv("HTTP_PROXY")
HTTPS_PROXY = os.getenv("HTTPS_PROXY")

# Path settings
DATA_ROOT_DIR = os.getenv("DATA_ROOT_DIR", "./data")
CHROMEDRIVER_PATH = os.getenv("CHROMEDRIVER_PATH", "/usr/local/bin/chromedriver")

NEWSCASTCHER_KEY = ""

OPENAI_KEY = os.getenv("OPENAI_KEY")
ANTHROPIC_KEY = ""
TOGETHER_KEY = ""
GOOGLE_AI_KEY = ""
HF_ACCESS_TOKEN = ""

keys = {
    # "AWS_ACCESS_KEY": AWS_ACCESS_KEY,
    # "AWS_SECRET_KEY": AWS_SECRET_KEY,

    "METACULUS_KEY": METACULUS_KEY,
    "MANIFOLD_KEY": MANIFOLD_KEY,
    "POLYMARKET_KEY": POLYMARKET_KEY,
    "CRYPTO_PRIVATE_KEY": CRYPTO_PRIVATE_KEY,
    "EMAIL": EMAIL,
    "GJOPEN_CSET_PASSWORD": GJOPEN_CSET_PASSWORD,

    # Proxy settings
    "HTTP_PROXY": HTTP_PROXY,
    "HTTPS_PROXY": HTTPS_PROXY,
    
    # Path settings
    "DATA_ROOT_DIR": DATA_ROOT_DIR,
    "CHROMEDRIVER_PATH": CHROMEDRIVER_PATH,

    "NEWSCASTCHER_KEY": NEWSCASTCHER_KEY,

    "OPENAI_KEY": OPENAI_KEY,
    "ANTHROPIC_KEY": ANTHROPIC_KEY,
    "TOGETHER_KEY": TOGETHER_KEY,
    "GOOGLE_AI_KEY": GOOGLE_AI_KEY,
    "HF_ACCESS_TOKEN": HF_ACCESS_TOKEN,
}
